Tweaked evaluation and worksheet template, Added Gnomesort Evaluations and Exercises, Added Splay Trees, Closes #10
mgoadric/cs2mulch pull request #22
Opened 2024-05-18 07:59 UTC by qsebring3930

-I noticed that even though worksheets worked on my local server, they did not work when pushed to the actual website. It was a minor typo in the permalink that I fixed
-Long evaluation questions wrapped strange and made the evaluation portion look messy so I added extra div containers
-Added splay trees algorithm, video, and example
-Added about 20 exercises and 5 evaluation questions for Gnomesort

2024-05-21 14:14 UTC, mgoadric requested changes
Looks like a great setup! A few small corrections noted inline.

2024-05-21 14:14 UTC, mgoadric commented on _pages/splaytree.md
Missing a learning goals sentence here.

2024-05-21 14:14 UTC, mgoadric commented on _pages/splaytree.md
> +{% include figure image_path="/assets/images/splay14.png" alt="Tree splayed with Zig operation." caption="Tree splayed with Zig operation." %}
This last image is the same as the previous. Should it be splay15?

2024-05-25 00:28 UTC, qsebring3930 commented
Thanks for catching those, I corrected the image and added the learning goals.

2024-05-28 18:42 UTC, mgoadric commented
This looks excellent, great work! In tabletopia I think you can select multiple cards at the same time and move them together. Rotating them together is another story...

2024-05-28 18:42 UTC, merged

2024-06-01 05:25 UTC, qsebring3930 commented
I'll have to look into that and try recording the video again, I know I've picked up more than ine by accident before.